In [1]:
import sys
sys.path.append("../")

In [2]:
import torch
import TCSF

In [3]:
device = "cuda"

In [4]:
batch = 16
m = 1024

In [5]:
A_r = torch.nn.Parameter(torch.randn(batch,m,m,device=device))
A_i = torch.nn.Parameter(torch.zeros(batch,m,m,device=device))
b_r = torch.nn.Parameter(torch.randn(batch,m,1,device=device))
b_i = torch.nn.Parameter(torch.zeros(batch,m,1,device=device))
AA_r = torch.nn.Parameter(A_r.detach())
AA_i = torch.nn.Parameter(A_i.detach())
bb_r = torch.nn.Parameter(b_r.detach())
bb_i = torch.nn.Parameter(b_i.detach())

In [6]:
x,_ = torch.solve(b_r,A_r)

In [7]:
y=x.sum()
y.backward()

In [8]:
CS = TCSF.Csolver()
cx = CS(AA_r,AA_i,bb_r,bb_i)

In [9]:
xx = cx[0] + cx[1]
yy = xx.sum()
yy.backward()

In [10]:
x

tensor([[[ 0.5177],
         [-3.2051],
         [ 1.7605],
         ...,
         [-0.8493],
         [ 3.0120],
         [-1.3640]],

        [[ 0.2141],
         [ 3.7487],
         [-4.2691],
         ...,
         [-0.4041],
         [-4.3553],
         [ 1.9612]],

        [[-0.1894],
         [ 2.8421],
         [-0.7438],
         ...,
         [ 0.1000],
         [-1.4228],
         [ 0.7179]],

        ...,

        [[ 1.3833],
         [-1.9060],
         [-0.5826],
         ...,
         [ 0.0976],
         [-3.5897],
         [-1.0135]],

        [[-0.3578],
         [-0.0669],
         [-0.2019],
         ...,
         [-0.1756],
         [ 0.5401],
         [-0.0345]],

        [[-1.3286],
         [ 0.9774],
         [ 0.4920],
         ...,
         [-1.4715],
         [-2.9097],
         [-2.6907]]], device='cuda:0', grad_fn=<SolveBackward>)

In [11]:
cx

(tensor([[[ 0.5176],
          [-3.2048],
          [ 1.7604],
          ...,
          [-0.8491],
          [ 3.0120],
          [-1.3637]],
 
         [[ 0.2147],
          [ 3.7489],
          [-4.2694],
          ...,
          [-0.4043],
          [-4.3554],
          [ 1.9612]],
 
         [[-0.1894],
          [ 2.8412],
          [-0.7437],
          ...,
          [ 0.0998],
          [-1.4225],
          [ 0.7176]],
 
         ...,
 
         [[ 1.3832],
          [-1.9058],
          [-0.5824],
          ...,
          [ 0.0976],
          [-3.5894],
          [-1.0133]],
 
         [[-0.3578],
          [-0.0669],
          [-0.2018],
          ...,
          [-0.1756],
          [ 0.5401],
          [-0.0345]],
 
         [[-1.3285],
          [ 0.9775],
          [ 0.4919],
          ...,
          [-1.4712],
          [-2.9102],
          [-2.6911]]], device='cuda:0', grad_fn=<CsolverFunctionBackward>),
 tensor([[[0.],
          [-0.],
          [0.],
          ...,
    

In [12]:
A_r.grad

tensor([[[-6.1052e-01,  3.7797e+00, -2.0762e+00,  ...,  1.0016e+00,
          -3.5520e+00,  1.6086e+00],
         [ 2.5392e-01, -1.5720e+00,  8.6349e-01,  ..., -4.1658e-01,
           1.4773e+00, -6.6903e-01],
         [ 5.7315e-01, -3.5484e+00,  1.9491e+00,  ..., -9.4032e-01,
           3.3346e+00, -1.5102e+00],
         ...,
         [ 5.3163e-02, -3.2913e-01,  1.8079e-01,  ..., -8.7220e-02,
           3.0931e-01, -1.4008e-01],
         [ 2.3740e-01, -1.4697e+00,  8.0731e-01,  ..., -3.8948e-01,
           1.3812e+00, -6.2550e-01],
         [-7.3534e-01,  4.5524e+00, -2.5006e+00,  ...,  1.2064e+00,
          -4.2782e+00,  1.9375e+00]],

        [[-2.4591e-01, -4.3050e+00,  4.9026e+00,  ...,  4.6410e-01,
           5.0016e+00, -2.2523e+00],
         [ 3.6940e-03,  6.4668e-02, -7.3646e-02,  ..., -6.9716e-03,
          -7.5133e-02,  3.3833e-02],
         [-5.2897e-02, -9.2605e-01,  1.0546e+00,  ...,  9.9832e-02,
           1.0759e+00, -4.8448e-01],
         ...,
         [-6.4838e-03, -1

In [13]:
AA_r.grad

tensor([[[-6.1041e-01,  3.7795e+00, -2.0761e+00,  ...,  1.0014e+00,
          -3.5521e+00,  1.6082e+00],
         [ 2.5387e-01, -1.5719e+00,  8.6346e-01,  ..., -4.1648e-01,
           1.4773e+00, -6.6886e-01],
         [ 5.7309e-01, -3.5484e+00,  1.9492e+00,  ..., -9.4017e-01,
           3.3349e+00, -1.5099e+00],
         ...,
         [ 5.3305e-02, -3.3005e-01,  1.8130e-01,  ..., -8.7448e-02,
           3.1019e-01, -1.4044e-01],
         [ 2.3738e-01, -1.4698e+00,  8.0738e-01,  ..., -3.8943e-01,
           1.3814e+00, -6.2542e-01],
         [-7.3525e-01,  4.5525e+00, -2.5007e+00,  ...,  1.2062e+00,
          -4.2785e+00,  1.9371e+00]],

        [[-2.4654e-01, -4.3053e+00,  4.9031e+00,  ...,  4.6426e-01,
           5.0019e+00, -2.2524e+00],
         [ 3.7011e-03,  6.4631e-02, -7.3605e-02,  ..., -6.9694e-03,
          -7.5088e-02,  3.3812e-02],
         [-5.3040e-02, -9.2623e-01,  1.0548e+00,  ...,  9.9879e-02,
           1.0761e+00, -4.8457e-01],
         ...,
         [-6.5053e-03, -1

In [14]:
b_r.grad

tensor([[[ 1.1793],
         [-0.4905],
         [-1.1071],
         ...,
         [-0.1027],
         [-0.4586],
         [ 1.4204]],

        [[ 1.1484],
         [-0.0173],
         [ 0.2470],
         ...,
         [ 0.0303],
         [-0.0494],
         [-0.1048]],

        [[ 0.5999],
         [ 0.2649],
         [ 0.3614],
         ...,
         [ 1.6008],
         [ 3.5661],
         [ 1.6799]],

        ...,

        [[ 0.4344],
         [-0.5425],
         [ 0.7177],
         ...,
         [ 0.7039],
         [-1.5044],
         [-0.5140]],

        [[-0.8654],
         [-0.4290],
         [-0.8546],
         ...,
         [ 0.0524],
         [ 1.0876],
         [ 0.2202]],

        [[ 0.3647],
         [-0.9052],
         [ 0.1058],
         ...,
         [ 0.5528],
         [-0.3817],
         [ 0.5170]]], device='cuda:0')

In [15]:
bb_r.grad

tensor([[[ 1.1793],
         [-0.4905],
         [-1.1072],
         ...,
         [-0.1030],
         [-0.4586],
         [ 1.4205]],

        [[ 1.1484],
         [-0.0172],
         [ 0.2471],
         ...,
         [ 0.0303],
         [-0.0494],
         [-0.1048]],

        [[ 0.5999],
         [ 0.2648],
         [ 0.3612],
         ...,
         [ 1.6006],
         [ 3.5655],
         [ 1.6799]],

        ...,

        [[ 0.4347],
         [-0.5424],
         [ 0.7178],
         ...,
         [ 0.7037],
         [-1.5043],
         [-0.5143]],

        [[-0.8654],
         [-0.4290],
         [-0.8546],
         ...,
         [ 0.0524],
         [ 1.0877],
         [ 0.2202]],

        [[ 0.3647],
         [-0.9052],
         [ 0.1057],
         ...,
         [ 0.5528],
         [-0.3818],
         [ 0.5171]]], device='cuda:0')