In [1]:
import sys
sys.path.append("../")

In [2]:
import torch
import TCSF

In [3]:
device = "cuda"

In [4]:
batch = 3

In [5]:
A_r = torch.nn.Parameter(torch.randn(batch,4,4,device=device))
A_i = torch.nn.Parameter(torch.zeros(batch,4,4,device=device))
b_r = torch.nn.Parameter(torch.randn(batch,4,1,device=device))
b_i = torch.nn.Parameter(torch.zeros(batch,4,1,device=device))
AA_r = torch.nn.Parameter(A_r.detach())
AA_i = torch.nn.Parameter(A_i.detach())
bb_r = torch.nn.Parameter(b_r.detach())
bb_i = torch.nn.Parameter(b_i.detach())

In [6]:
x,_ = torch.solve(b_r,A_r)

In [7]:
y=x.sum()
y.backward()

In [8]:
CS = TCSF.Csolver()
cx = CS(AA_r,AA_i,bb_r,bb_i)

In [9]:
xx = cx[0] + cx[1]
yy = xx.sum()
yy.backward()

In [10]:
x

tensor([[[-3.8073],
         [-0.5619],
         [-4.8399],
         [-1.4416]],

        [[-0.0066],
         [-0.2324],
         [ 1.0617],
         [-1.2149]],

        [[ 0.2036],
         [-1.8926],
         [ 1.2092],
         [ 1.1606]]], device='cuda:0', grad_fn=<SolveBackward>)

In [11]:
cx

(tensor([[[-3.8073],
          [-0.5619],
          [-4.8399],
          [-1.4416]],
 
         [[-0.0066],
          [-0.2324],
          [ 1.0617],
          [-1.2149]],
 
         [[ 0.2036],
          [-1.8926],
          [ 1.2092],
          [ 1.1606]]], device='cuda:0', grad_fn=<CsolverFunctionBackward>),
 tensor([[[0.],
          [-0.],
          [0.],
          [-0.]],
 
         [[-0.],
          [0.],
          [0.],
          [-0.]],
 
         [[0.],
          [0.],
          [0.],
          [0.]]], device='cuda:0', grad_fn=<CsolverFunctionBackward>))

In [12]:
A_r.grad

tensor([[[ 1.4962e+01,  2.2083e+00,  1.9020e+01,  5.6652e+00],
         [-9.5806e+00, -1.4140e+00, -1.2179e+01, -3.6276e+00],
         [-1.8503e+00, -2.7309e-01, -2.3521e+00, -7.0059e-01],
         [-2.0461e+01, -3.0199e+00, -2.6010e+01, -7.7472e+00]],

        [[ 8.5774e-03,  3.0343e-01, -1.3861e+00,  1.5862e+00],
         [-4.4573e-04, -1.5768e-02,  7.2031e-02, -8.2425e-02],
         [-3.1055e-03, -1.0986e-01,  5.0185e-01, -5.7427e-01],
         [-4.8408e-04, -1.7124e-02,  7.8229e-02, -8.9517e-02]],

        [[-1.0953e-01,  1.0181e+00, -6.5043e-01, -6.2432e-01],
         [ 2.2508e-01, -2.0920e+00,  1.3366e+00,  1.2829e+00],
         [ 1.1850e-01, -1.1014e+00,  7.0369e-01,  6.7544e-01],
         [ 4.1182e-01, -3.8276e+00,  2.4454e+00,  2.3472e+00]]],
       device='cuda:0')

In [13]:
AA_r.grad

tensor([[[ 1.4962e+01,  2.2083e+00,  1.9020e+01,  5.6652e+00],
         [-9.5806e+00, -1.4140e+00, -1.2179e+01, -3.6276e+00],
         [-1.8503e+00, -2.7309e-01, -2.3521e+00, -7.0059e-01],
         [-2.0461e+01, -3.0199e+00, -2.6010e+01, -7.7472e+00]],

        [[ 8.5774e-03,  3.0343e-01, -1.3861e+00,  1.5862e+00],
         [-4.4573e-04, -1.5768e-02,  7.2031e-02, -8.2425e-02],
         [-3.1055e-03, -1.0986e-01,  5.0185e-01, -5.7427e-01],
         [-4.8408e-04, -1.7124e-02,  7.8229e-02, -8.9517e-02]],

        [[-1.0953e-01,  1.0181e+00, -6.5043e-01, -6.2432e-01],
         [ 2.2508e-01, -2.0920e+00,  1.3366e+00,  1.2829e+00],
         [ 1.1850e-01, -1.1014e+00,  7.0369e-01,  6.7544e-01],
         [ 4.1182e-01, -3.8276e+00,  2.4454e+00,  2.3472e+00]]],
       device='cuda:0')

In [14]:
b_r.grad

tensor([[[ 3.9298],
         [-2.5163],
         [-0.4860],
         [-5.3740]],

        [[ 1.3056],
         [-0.0678],
         [-0.4727],
         [-0.0737]],

        [[ 0.5379],
         [-1.1053],
         [-0.5820],
         [-2.0224]]], device='cuda:0')

In [15]:
bb_r.grad

tensor([[[ 3.9298],
         [-2.5163],
         [-0.4860],
         [-5.3740]],

        [[ 1.3056],
         [-0.0678],
         [-0.4727],
         [-0.0737]],

        [[ 0.5379],
         [-1.1053],
         [-0.5820],
         [-2.0224]]], device='cuda:0')