In [1]:
import torch
import solvers as TCS

In [2]:
device = "cuda"

In [3]:
#A,b = torch.randn(4,4).to(device),torch.rand(4).to(device)
A = torch.tensor([
    [1.0,2,3],
    [4,5,6],
    [7,8,10]]).to(device)
# b = torch.tensor([1.0,2,3]).to(device).reshape(-1,1)
b = torch.tensor([
    [1.0,2,],
    [2,4],
    [3,6]]).to(device)
# A = torch.tensor([[1.0,2,3,3],[4,5,6,6],[7,8,10,10],[10,11,10,11]]).to(device)
# b = torch.tensor([1.0,2,3,4]).to(device)

In [4]:
TCS.torch_real_solve(A,b)

(tensor([[-3.3333e-01, -6.6667e-01],
         [ 6.6667e-01,  1.3333e+00],
         [-1.1921e-07, -2.3842e-07]], device='cuda:0'),
 tensor([[ 7.0000,  8.0000, 10.0000],
         [ 0.1429,  0.8571,  1.5714],
         [ 0.5714,  0.5000, -0.5000]], device='cuda:0'))

In [5]:
TCS.torch_real_solve(A,b,use_cuSol=False)

torch.return_types.solve(
solution=tensor([[-3.3333e-01, -6.6667e-01],
        [ 6.6667e-01,  1.3333e+00],
        [-1.1921e-07, -2.3842e-07]], device='cuda:0'),
LU=tensor([[ 7.0000,  8.0000, 10.0000],
        [ 0.1429,  0.8571,  1.5714],
        [ 0.5714,  0.5000, -0.5000]], device='cuda:0'))

In [6]:
rand_A = torch.randn(4,4,device=device)
rand_b = torch.randn(4,1,device=device)

In [7]:
TCS.torch_real_solve(rand_A,rand_b)

(tensor([[-0.1880],
         [-0.4425],
         [ 0.2280],
         [-0.4233]], device='cuda:0'),
 tensor([[ 2.4729,  1.1350,  1.5283, -1.4916],
         [ 0.5984, -2.4509, -1.0675, -0.4214],
         [ 0.2522,  0.6488,  0.7853,  0.0543],
         [ 0.4444, -0.1979,  0.8406,  1.5429]], device='cuda:0'))

In [8]:
TCS.torch_real_solve(rand_A,rand_b,use_cuSol=False)

torch.return_types.solve(
solution=tensor([[-0.1880],
        [-0.4425],
        [ 0.2280],
        [-0.4233]], device='cuda:0'),
LU=tensor([[ 2.4729,  1.1350,  1.5283, -1.4916],
        [ 0.5984, -2.4509, -1.0675, -0.4214],
        [ 0.2522,  0.6488,  0.7853,  0.0543],
        [ 0.4444, -0.1979,  0.8406,  1.5429]], device='cuda:0'))