In [1]:
import sys
sys.path.append("../")

In [2]:
import torch
import solvers as TCS

In [3]:
device = "cuda"

In [4]:
A_r = torch.tensor([
    [1,2,3.0],
    [4,5,6],
    [7,8,10]
    ]
    ,device=device)
A_i = torch.zeros((3,3),device=device,dtype=A_r.dtype)

b_r = torch.tensor([
    [1.0],
    [2],
    [3]
    ]
    ,device=device)
b_i = torch.tensor([
    [2.0],
    [4],
    [6]
    ]
    ,device=device)

In [5]:
TCS.torch_complex_solve(A_r,A_i,b_r,b_i)

(tensor([[-3.3333e-01],
         [ 6.6667e-01],
         [-1.1921e-07]], device='cuda:0'),
 tensor([[-6.6667e-01],
         [ 1.3333e+00],
         [-2.3842e-07]], device='cuda:0'),
 tensor([[ 7.0000,  8.0000, 10.0000],
         [ 0.1429,  0.8571,  1.5714],
         [ 0.5714,  0.5000, -0.5000]], device='cuda:0'),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]], device='cuda:0'))

In [6]:
TCS.torch_complex_solve(A_r,A_i,b_r,b_i,use_cuSol=False)

array([[[-0.33333334-0.6666667j],
        [ 0.6666667 +1.3333334j],
        [ 0.        -0.j       ]]], dtype=complex64)

In [7]:
rand_A = torch.randn(2,4,4,device=device)
rand_b = torch.randn(2,4,1,device=device)

In [8]:
TCS.torch_complex_solve(rand_A[0],rand_A[1],rand_b[0],rand_b[1])

(tensor([[-1.5243],
         [-1.4131],
         [ 0.4323],
         [ 0.1102]], device='cuda:0'),
 tensor([[-0.1622],
         [ 1.2698],
         [-0.2766],
         [ 1.1611]], device='cuda:0'),
 tensor([[-0.4023,  0.6659,  1.6229, -1.1233],
         [ 0.1200, -0.7125, -1.0538, -0.0760],
         [ 0.1873,  0.4314,  1.1922,  1.0324],
         [-0.5867,  0.0403,  0.4047,  2.0669]], device='cuda:0'),
 tensor([[-1.4494,  0.4711,  0.6199, -0.1214],
         [-0.3016,  1.3325,  1.1698, -0.1023],
         [ 0.4654,  0.5949, -1.4365,  1.6444],
         [-0.3486, -0.4762,  1.0162, -1.9769]], device='cuda:0'))

In [9]:
TCS.torch_complex_solve(rand_A[0],rand_A[1],rand_b[0],rand_b[1],use_cuSol=False)

array([[[-1.5242593 -0.16220109j],
        [-1.4130505 +1.2697598j ],
        [ 0.43234715-0.27660075j],
        [ 0.1102053 +1.1610761j ]]], dtype=complex64)