In [1]:
import torch
import TCSF

In [2]:
device = "cuda"

In [3]:
A_r = torch.nn.Parameter(torch.randn(4,4,device=device))
A_i = torch.nn.Parameter(torch.zeros(4,4,device=device))
b_r = torch.nn.Parameter(torch.randn(4,1,device=device))
b_i = torch.nn.Parameter(torch.zeros(4,1,device=device))
AA_r = torch.nn.Parameter(A_r.detach())
AA_i = torch.nn.Parameter(A_i.detach())
bb_r = torch.nn.Parameter(b_r.detach())
bb_i = torch.nn.Parameter(b_i.detach())

In [4]:
x,_ = torch.solve(b_r,A_r)

In [5]:
y=x.sum()
#y.backward()

In [6]:
CS = TCSF.Csolver()
cx = CS(A_r,A_i,b_r,b_i)

In [7]:
xx = cx[0] + cx[1]
#yy.backward()

In [8]:
x

tensor([[-2.6333],
        [-0.4695],
        [-2.0001],
        [ 0.4523]], device='cuda:0', grad_fn=<SolveBackward>)

In [9]:
cx

tensor([[[-2.6333],
         [-0.4695],
         [-2.0001],
         [ 0.4523]],

        [[-0.0000],
         [ 0.0000],
         [-0.0000],
         [ 0.0000]]], device='cuda:0', grad_fn=<CsolverFunctionBackward>)

In [10]:
g = torch.randn(4,1,device=device)

In [11]:
x.grad_fn(g)

(tensor([[ 0.2417],
         [-0.0594],
         [ 0.4334],
         [-0.0590]], device='cuda:0', grad_fn=<SolveBackward>),
 tensor([[ 0.6365,  0.1135,  0.4834, -0.1093],
         [-0.1564, -0.0279, -0.1188,  0.0269],
         [ 1.1411,  0.2035,  0.8668, -0.1960],
         [-0.1553, -0.0277, -0.1180,  0.0267]], device='cuda:0',
        grad_fn=<NegBackward>))

In [12]:
cx.grad_fn(g)

TypeError: 'CsolverFunctionBackward' object is not callable

In [14]:
dir(cx.grad_fn)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_do_backward',
 '_do_forward',
 '_forward_cls',
 '_is_legacy',
 '_register_hook',
 '_register_hook_dict',
 'apply',
 'dirty_tensors',
 'mark_dirty',
 'mark_non_differentiable',
 'mark_shared_storage',
 'metadata',
 'needs_input_grad',
 'next_functions',
 'non_differentiable',
 'register_hook',
 'requires_grad',
 'save_for_backward',
 'saved_tensors',
 'saved_variables',
 'to_save']