# Test : ToCS really returns correct gradient?
Let's compare ToCS to PyTorch in real value.

In [1]:
import sys
sys.path.append("../")

In [2]:
import torch
import tocs

In [3]:
device = "cuda"

In [4]:
batch = 16
m = 1024

In [5]:
# set imag is zero
A_r = torch.nn.Parameter(torch.randn(batch,m,m,device=device))
A_i = torch.nn.Parameter(torch.zeros(batch,m,m,device=device))
b_r = torch.nn.Parameter(torch.randn(batch,m,1,device=device))
b_i = torch.nn.Parameter(torch.zeros(batch,m,1,device=device))
AA_r = torch.nn.Parameter(A_r.detach())
AA_i = torch.nn.Parameter(A_i.detach())
bb_r = torch.nn.Parameter(b_r.detach())
bb_i = torch.nn.Parameter(b_i.detach())

In [6]:
x,_ = torch.solve(b_r,A_r)

In [7]:
y=x.sum()
y.backward()

In [8]:
cx = tocs.Csolve(bb_r,bb_i,AA_r,AA_i)

In [9]:
xx = cx[0] + cx[1]
yy = xx.sum()
yy.backward()

In [10]:
x

tensor([[[ -0.6089],
         [ -5.1238],
         [ -6.6977],
         ...,
         [-18.0253],
         [  3.6473],
         [ -5.9538]],

        [[ -1.7277],
         [  2.2745],
         [  0.4537],
         ...,
         [  0.8640],
         [  0.3097],
         [  1.3374]],

        [[  0.5562],
         [ -0.7670],
         [ -0.6322],
         ...,
         [ -1.1189],
         [  1.4524],
         [  1.3377]],

        ...,

        [[ -3.0584],
         [ -2.7716],
         [  4.2648],
         ...,
         [ -1.0321],
         [  2.7041],
         [  3.4357]],

        [[ -2.1213],
         [  3.9642],
         [-10.4424],
         ...,
         [ -1.0619],
         [ -3.2337],
         [ -6.4407]],

        [[ -0.1658],
         [ -0.1463],
         [ -0.3278],
         ...,
         [ -0.1769],
         [  0.3014],
         [ -0.3065]]], device='cuda:0', grad_fn=<SolveBackward>)

In [11]:
cx

(tensor([[[ -0.6103],
          [ -5.1327],
          [ -6.7056],
          ...,
          [-18.0551],
          [  3.6519],
          [ -5.9628]],
 
         [[ -1.7277],
          [  2.2746],
          [  0.4536],
          ...,
          [  0.8640],
          [  0.3097],
          [  1.3374]],
 
         [[  0.5563],
          [ -0.7669],
          [ -0.6322],
          ...,
          [ -1.1190],
          [  1.4527],
          [  1.3377]],
 
         ...,
 
         [[ -3.0579],
          [ -2.7723],
          [  4.2656],
          ...,
          [ -1.0319],
          [  2.7048],
          [  3.4366]],
 
         [[ -2.1220],
          [  3.9656],
          [-10.4460],
          ...,
          [ -1.0632],
          [ -3.2350],
          [ -6.4412]],
 
         [[ -0.1658],
          [ -0.1464],
          [ -0.3278],
          ...,
          [ -0.1769],
          [  0.3014],
          [ -0.3064]]], device='cuda:0', grad_fn=<CsolverFunctionBackward>),
 tensor([[[-0.],
          [-0.]

In [12]:
A_r.grad

tensor([[[-4.8782e+01, -4.1048e+02, -5.3657e+02,  ..., -1.4440e+03,
           2.9220e+02, -4.7697e+02],
         [-2.6326e+01, -2.2152e+02, -2.8957e+02,  ..., -7.7932e+02,
           1.5769e+02, -2.5741e+02],
         [ 2.9995e+01,  2.5239e+02,  3.2993e+02,  ...,  8.8792e+02,
          -1.7967e+02,  2.9328e+02],
         ...,
         [ 2.3437e+01,  1.9721e+02,  2.5779e+02,  ...,  6.9378e+02,
          -1.4038e+02,  2.2916e+02],
         [-7.9243e-01, -6.6679e+00, -8.7162e+00,  ..., -2.3458e+01,
           4.7465e+00, -7.7481e+00],
         [-2.9121e+01, -2.4504e+02, -3.2031e+02,  ..., -8.6204e+02,
           1.7443e+02, -2.8473e+02]],

        [[ 4.2123e-02, -5.5455e-02, -1.1062e-02,  ..., -2.1066e-02,
          -7.5508e-03, -3.2608e-02],
         [-1.4524e+00,  1.9121e+00,  3.8141e-01,  ...,  7.2637e-01,
           2.6036e-01,  1.1243e+00],
         [-1.1371e+00,  1.4970e+00,  2.9861e-01,  ...,  5.6867e-01,
           2.0383e-01,  8.8024e-01],
         ...,
         [-1.8812e-01,  2

In [13]:
AA_r.grad

tensor([[[-4.8864e+01, -4.1097e+02, -5.3691e+02,  ..., -1.4457e+03,
           2.9241e+02, -4.7744e+02],
         [-2.6371e+01, -2.2179e+02, -2.8976e+02,  ..., -7.8020e+02,
           1.5781e+02, -2.5767e+02],
         [ 3.0045e+01,  2.5270e+02,  3.3013e+02,  ...,  8.8890e+02,
          -1.7979e+02,  2.9357e+02],
         ...,
         [ 2.3479e+01,  1.9747e+02,  2.5798e+02,  ...,  6.9463e+02,
          -1.4050e+02,  2.2941e+02],
         [-7.9165e-01, -6.6583e+00, -8.6986e+00,  ..., -2.3422e+01,
           4.7374e+00, -7.7352e+00],
         [-2.9174e+01, -2.4537e+02, -3.2056e+02,  ..., -8.6312e+02,
           1.7458e+02, -2.8505e+02]],

        [[ 4.1993e-02, -5.5284e-02, -1.1025e-02,  ..., -2.1000e-02,
          -7.5279e-03, -3.2504e-02],
         [-1.4527e+00,  1.9125e+00,  3.8140e-01,  ...,  7.2646e-01,
           2.6042e-01,  1.1244e+00],
         [-1.1372e+00,  1.4971e+00,  2.9856e-01,  ...,  5.6867e-01,
           2.0385e-01,  8.8021e-01],
         ...,
         [-1.8809e-01,  2

In [14]:
b_r.grad

tensor([[[-8.0112e+01],
         [-4.3235e+01],
         [ 4.9260e+01],
         ...,
         [ 3.8489e+01],
         [-1.3014e+00],
         [-4.7824e+01]],

        [[ 2.4381e-02],
         [-8.4067e-01],
         [-6.5816e-01],
         ...,
         [-1.0888e-01],
         [ 6.1901e-01],
         [-2.5219e-01]],

        [[ 1.4496e+00],
         [-4.1471e-01],
         [ 9.0890e-02],
         ...,
         [ 1.5649e-01],
         [-8.9084e-01],
         [ 2.6667e+00]],

        ...,

        [[ 1.7163e-01],
         [ 2.9495e+00],
         [ 5.7960e-01],
         ...,
         [-4.0295e-01],
         [-1.0776e+00],
         [-1.9305e+00]],

        [[-1.3032e+00],
         [ 3.6734e+00],
         [-2.6525e+00],
         ...,
         [ 1.2775e+01],
         [-4.1260e+00],
         [ 7.7251e+00]],

        [[ 6.7559e-01],
         [-2.1508e-01],
         [-6.8939e-01],
         ...,
         [-1.2227e+00],
         [-5.6480e-01],
         [ 7.6358e-01]]], device='cuda:0')

In [15]:
bb_r.grad

tensor([[[-8.0070e+01],
         [-4.3212e+01],
         [ 4.9233e+01],
         ...,
         [ 3.8473e+01],
         [-1.2972e+00],
         [-4.7805e+01]],

        [[ 2.4305e-02],
         [-8.4079e-01],
         [-6.5818e-01],
         ...,
         [-1.0887e-01],
         [ 6.1891e-01],
         [-2.5220e-01]],

        [[ 1.4497e+00],
         [-4.1482e-01],
         [ 9.0616e-02],
         ...,
         [ 1.5656e-01],
         [-8.9071e-01],
         [ 2.6667e+00]],

        ...,

        [[ 1.7170e-01],
         [ 2.9493e+00],
         [ 5.7961e-01],
         ...,
         [-4.0311e-01],
         [-1.0775e+00],
         [-1.9306e+00]],

        [[-1.3031e+00],
         [ 3.6736e+00],
         [-2.6523e+00],
         ...,
         [ 1.2776e+01],
         [-4.1274e+00],
         [ 7.7263e+00]],

        [[ 6.7556e-01],
         [-2.1502e-01],
         [-6.8936e-01],
         ...,
         [-1.2226e+00],
         [-5.6485e-01],
         [ 7.6349e-01]]], device='cuda:0')

In big tensor, small error occurs. The difference perphaps comes from the differenc between solvers; cuSolve which ToCS uses and solver which torch uses (Magma?).