In [1]:
import torch
import solvers as TCS

In [2]:
device = "cuda"

In [3]:
A_r = torch.tensor([
    [1,2,3.0],
    [4,5,6],
    [7,8,10]
    ]
    ,device=device)
A_i = torch.zeros((3,3),device=device,dtype=A_r.dtype)

b_r = torch.tensor([
    [1.0],
    [2],
    [3]
    ]
    ,device=device)
b_i = torch.tensor([
    [2.0],
    [4],
    [6]
    ]
    ,device=device)

In [4]:
TCS.torch_complex_solve(A_r,A_i,b_r,b_i)

(tensor([[-3.3333e-01],
         [ 6.6667e-01],
         [-1.1921e-07]], device='cuda:0'),
 tensor([[-6.6667e-01],
         [ 1.3333e+00],
         [-2.3842e-07]], device='cuda:0'),
 tensor([[ 7.0000,  8.0000, 10.0000],
         [ 0.1429,  0.8571,  1.5714],
         [ 0.5714,  0.5000, -0.5000]], device='cuda:0'),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]], device='cuda:0'))

In [5]:
TCS.torch_complex_solve(A_r,A_i,b_r,b_i,use_cuSol=False)

array([[[-0.33333334-0.6666667j],
        [ 0.6666667 +1.3333334j],
        [ 0.        -0.j       ]]], dtype=complex64)

In [6]:
rand_A = torch.randn(2,4,4,device=device)
rand_b = torch.randn(2,4,1,device=device)

In [7]:
TCS.torch_complex_solve(rand_A[0],rand_A[1],rand_b[0],rand_b[1])

(tensor([[-0.3527],
         [ 0.4357],
         [-1.2532],
         [-0.4911]], device='cuda:0'),
 tensor([[ 2.9530],
         [-0.3441],
         [-1.0551],
         [ 0.9212]], device='cuda:0'),
 tensor([[ 0.5631,  0.8037, -0.6332,  0.9159],
         [ 0.3126,  1.7740,  0.4708, -0.1018],
         [-0.0096,  0.3188,  1.0195,  3.2443],
         [ 0.0154, -0.0541, -0.1600,  0.9196]], device='cuda:0'),
 tensor([[ 1.6497,  0.7841,  2.2484,  0.0220],
         [-0.0835,  0.4011, -0.2211, -0.3586],
         [ 0.8393, -0.5371,  0.7128, -2.3624],
         [-0.4300,  0.4690, -0.2464,  1.8051]], device='cuda:0'))

In [8]:
TCS.torch_complex_solve(rand_A[0],rand_A[1],rand_b[0],rand_b[1],use_cuSol=False)

array([[[-0.35267758+2.9530058j ],
        [ 0.4357436 -0.3441016j ],
        [-1.2532456 -1.0550859j ],
        [-0.4910985 +0.92117286j]]], dtype=complex64)